- name: vard from files
  hosts: local
  connection: local
  tasks:
  - name: print the variable from vars_files
    ansible.builtin.debug:
      msg: "This is a variable from vars_files: {{ COURSE }} and {{ DURATION }}"
     