- name: vars from inventory
  hosts: local
  connection: local
  tasks:
  - name: print the variables from inventory
    ansible.builtin.debug:
      msg: "This is a variable from inventory: {{ Name }} and {{ Role }} and {{ salary }}"